/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author chamidi
 */
public class LoadingP extends javax.swing.JFrame {

    /** Creates new form LoadingP */
    public LoadingP() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        Loading = new javax.swing.JLabel();
        Num = new javax.swing.JProgressBar();
        loadingimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Loading.setText("Loading........");
        backgroundPanel.add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 300, -1));
        backgroundPanel.add(Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 578, 1000, 30));

        loadingimage.setIcon(new javax.swing.ImageIcon("C:\\Users\\chamidi\\Desktop\\icons\\loading page.jpg")); // NOI18N
        backgroundPanel.add(loadingimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 568));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        LoadingP sp = new LoadingP();
        sp.setVisible(true);
        
        StartP start = new StartP();
         
    
        
    try{
        for (int i=0;i<=100;i++){
            Thread.sleep(50);
            sp.Num.setValue(i);
            
            
            if (i==10){
                sp.Loading.setText("CONNECT TO THE SERVER....");
            }
            if (i==20){
                sp.Loading.setText("LOADING TO THE SERVER....");
            }
            
            if (i==50){
                sp.Loading.setText("CONNECTING YOUR DATABASE....");
            }
            
            if (i==70){
                sp.Loading.setText("CONNECTION SUCCESSFULLY....");
            }
            
            if (i==80){
                sp.Loading.setText("LOUNCHING THE MATHS++ GAME....");
            }
            sp.Num.setValue(i);
        }
        sp.setVisible(false);
        start.setVisible(true);
         
    
        
    }catch (Exception e){
        
        
    }
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loading;
    private javax.swing.JProgressBar Num;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel loadingimage;
    // End of variables declaration//GEN-END:variables

}
